# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

lang: en
timezone: America/New_York

title: Bioinformaniac
tagline: Training models on life itself.

description: >-
  Bioinformaniac is my ongoing journey to becoming a better bioinformatician — one step, one script at a time. As I explore the foundations of machine learning and move toward AI and neural networks, this blog captures the lessons, breakthroughs, and challenges along the way. From sequencing data to model training, it’s all part of the learning curve.

avatar: assets/img/avtar.jpeg

url: "https://tushar-bioinfo.github.io"
baseurl: "/learning-bioinformatics"

github:
  username: tushar-bioinfo

social:
  name: Tushar Singh
  email: tushar14032001@gmail.com
  links:
    - https://github.com/tushar-bioinfo

theme_mode: dark

toc: true

pwa:
  enabled: true
  cache:
    enabled: true

paginate: 10

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

collections:
  tabs:
    output: true
    sort_by: order

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]


sidebar:
  nav_list:
    - title: Projects
      url: /projects/
    - title: Links
      url: /links/
    - title: About
      url: /about/


exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
